### ISSUE TITLE
Separate module for video processing logic and hadoop

### ISSUE THREAD

**Issue by smadha** [USCDataScience/pooled_time_series#12]
We should seperate video processing classes like [Pot.java](https://github.com/USCDataScience/hadoop-pot/blob/5ddddbb06ebb88f7f0d73fee12f846b9268199e7/src/main/java/org/pooledtimeseries/PoT.java) with hadoop classes like [OpticalTimeSeries.java](https://github.com/USCDataScience/hadoop-pot/blob/5ddddbb06ebb88f7f0d73fee12f846b9268199e7/src/main/java/org/pooledtimeseries/OpticalTimeSeries.java)

My suggestion is to push below two maven modules in maven central -
1. pooled-time-series.jar built from https://github.com/mryoo/pooled_time_series
2. hadoop-pot.jar built from this repository

hadoop-pot should pull pooled-time-series.jar from central as maven dependency.

**Comment by smadha** [comment]
After discussions we are converting this project into multi module maven project. Separating video processing logic and hadoop.

Module names -
1. hadoop-pot-app
2. hadoop-pot-video

@chrismattmann These names sounds fine?

**Comment by chrismattmann** [comment]
how about:
1. hadoop-pot-video - OpenCV and PoT impl
2. hadoop-pot-core - hadoop stuff

Cool?

**Comment by smadha** [comment]
Cool
