### ISSUE TITLE
Documentation is out of sync

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/pooled_time_series#7]
@smadha Can you describe the parameters to the `SimilarityCalculation` job

This is said in ReadMe, but not very clear:

```
# Run the similarity job (using the value calculated in the previous job)
hadoop jar target/pooled-time-series-1.0-SNAPSHOT-jar-with-dependencies.jar  \
org.pooledtimeseries.SimilarityCalculation SimilarityInput/ SimilarityOutput/ ./MeanChiOutput/meanChiSquaredDistances.txt
```

**Comment by smadha** [comment]
Boom right in time TG

I am documenting execution details in wiki and below might help
https://github.com/USCDataScience/hadoop-pot/wiki/Individual-MR-job-commands

I will soon write pages describing task of each job.

@chrismattmann @thammegowda

**Comment by smadha** [comment]
@thammegowda If you are looking at improving architecture please add your work on https://github.com/USCDataScience/hadoop-pot/issues/5

**Comment by chrismattmann** [comment]
OK if we are working on the wiki we need to reference it now in the README @smadha

**Comment by smadha** [comment]
Let me update README too
I plan to more wiki pages. one per job

**Comment by chrismattmann** [comment]
yes, fine. I've now removed docs out of README and referenced the wiki. Should have been a first step.
